# Generated by Django 4.2.7 on 2023-11-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
