# Generated by Django 4.2.7 on 2023-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='started',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
