# Generated by Django 4.2.7 on 2023-11-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_teacher_quote_teacher_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
