# Generated by Django 4.2.7 on 2023-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_teacher_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
