# Generated by Django 4.2.7 on 2023-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
