# Generated by Django 4.2.7 on 2023-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_teacher_photo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
