# Generated by Django 4.2.7 on 2023-11-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_alter_class_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
