# Generated by Django 4.2.7 on 2023-11-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_artwork_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='code',
        ),
    ]
