# Generated by Django 4.2.7 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_remove_artwork_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
